### ISSUE TITLE
Thoughts about "change IDL sequence<>s from TS Arrays to Iterables"

### ISSUE THREAD

**Issue by coding-001** [gpuweb/types#14]
https://github.com/gpuweb/types/commit/fe48b1442891713af7bca9283c4be7e283ca54e9#diff-b5b64e96553740eb6242c03138cb64d4L347

vertexBuffers?: GPUVertexBufferLayoutDescriptor[];
was changed to
vertexBuffers?: Iterable<GPUVertexBufferLayoutDescriptor>;

But now I can not vertexBuffers.push or vertexBuffers[0]

**Comment by kainino0x** [comment]
This change is necessary to allow code that's valid in the browser, but would have been rejected by the types. Here are two options to work around it:

```
const vertexBuffers: GPUVertexBufferLayoutDescriptor[] = [];
const vertexState: GPUVertexStateDescriptor = { vertexBuffers };

vertexBuffers.push(...);
```

or

```
// No type annotation, allow it to do type inference.
// (Or, if you need a type annotation, define your own version of
// MyGPUVertexStateDescriptor that does have an array there -
// it will be a valid subtype of GPUVertexStateDescriptor.)
const vertexState = {
  vertexBuffers: [],
};

vertexState.vertexBuffers.push[];

// (use vertexState as if it were a GPUVertexStateDescriptor,
// as it should be a valid subtype.)
```

With the latter approach with type inference, you may run into cases
where a `"string literal"` will be inferred as type `string` instead of
an enum type. In those cases you can use the `constants` file from this
package, e.g. `C.VertexFormat.Float` ([example code](https://github.com/gpuweb/cts/blob/master/src/suites/cts/validation/vertex_state.spec.ts#L434)).

**Comment by coding-001** [comment]
Or: (renderPassDescriptor.colorAttachments as Array<GPURenderPassColorAttachmentDescriptor>)[0].attachment = swapChain.getCurrentTexture().createView();
Or: I just keep use [] but not Iterable

**Comment by kainino0x** [comment]
> With the latter approach with type inference, you may run into cases
> where a `"string literal"` will be inferred as type `string` instead of
> an enum type. In those cases you can use the `constants` file from this
> package, e.g. `C.VertexFormat.Float` ([example code](https://github.com/gpuweb/cts/blob/master/src/suites/cts/validation/vertex_state.spec.ts#L434)).

I recently realized you can just use `'float' as const` for a similar effect in most cases, instead of having to use `constants.ts`.

Anyway, closing as I think this is resolved.
