### ISSUE TITLE
`undefined` cannot be accepted as a member of `GPUPipelineLayoutDescriptor.bindGroupLayouts`

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/types#162]
Now in dist/index.d.ts `GPUPipelineLayoutDescriptor` is defined as below, which means the member of `bindGroupLayouts` in `GPUPipelineLayoutDescriptor` can not be `undefined`:

```JavaScript
interface GPUPipelineLayoutDescriptor
  extends GPUObjectDescriptorBase {
  /**
   * A list of optional {@link GPUBindGroupLayout}s the pipeline will use. Each element corresponds
   * to a @group attribute in the {@link GPUShaderModule}, with the `N`th element corresponding
   * with `@group(N)`.
   */
  bindGroupLayouts: Iterable<GPUBindGroupLayout | null>;
}
```

While according to [WebGPU SPEC](https://gpuweb.github.io/gpuweb/#pipeline-layout-creation), `undefined` is valid as a member of `bindGroupLayouts` in `GPUPipelineLayoutDescriptor`:

```Javascript
dictionary GPUPipelineLayoutDescriptor
         : GPUObjectDescriptorBase {
    required sequence<GPUBindGroupLayout?> bindGroupLayouts;
};
```

Does it mean the definition of `GPUPipelineLayoutDescriptor` in dist/index.d.ts doesn't follow the WebGPU SPEC?

**Comment by kainino0x** [comment]
You're correct, WebIDL `T?` should be translated as `T | null | undefined`.

It would be best to fix this in the generator, but if that's difficult we can fix it in `dist/index.d.ts` and add a note in https://github.com/gpuweb/types/blob/main/README.md#intentional-differences-between-generator-output-and-final-result
