### ISSUE TITLE
mappedAtCreation missing

### ISSUE THREAD

**Issue by baptistemanson** [gpuweb/types#19]
GPUBufferDescriptor is supposed to accept mappedAtCreation.
https://gpuweb.github.io/gpuweb/#GPUBufferDescriptor

But it is missing from the type.
https://github.com/gpuweb/types/blob/master/dist/index.d.ts#L296

Do you manually edit the types or generate them from the specs? I can fix it no problem.

**Comment by kainino0x** [comment]
They are edited manually.
We keep a comment at the top that describes exactly the state of the types relative to the spec:
https://github.com/gpuweb/types/blob/master/dist/index.d.ts#L1

If you open a PR, you can either:
- Just add the changes in https://github.com/gpuweb/gpuweb/pull/708
- Update the whole thing to the latest spec

However, note that mappedAtCreation was just added. It's definitely not implemented in Chrome and I doubt it's already implemented anywhere else (since we are still planning to rename these entries anyway https://github.com/gpuweb/gpuweb/issues/796). So unless you have a specific need for it now, you can wait for us to update the types. (It will happen not too long after the implementation changes, because we need to update the types in order to update the conformance test suite.)

**Comment by baptistemanson** [comment]
Thank you! I will wait and let you drive it at the pace that makes sense for y'all :).
