### ISSUE TITLE
Remove "src" folder from npm package

### ISSUE THREAD

**Issue by zackify** [gpuweb/types#30]
I installed this types package, and then added: 

```
"typeRoots": [
        "./node_modules/@webgpu/types",
      ]
```
to my tsconfig.json, when compiling it throws an error: 

```
Cannot find type definition file for 'src'.
```

Pretty sure if we just remove the src folder (add an `.npmignore`) it will go away. I can make a pr if you want?

**Comment by kainino0x** [comment]
src/ is in the package due to this line: https://github.com/gpuweb/types/blob/main/package.json#L12

The reason for that is that I had a dependent project (gpuweb/cts) which was file-copying that file out of this package. It's no longer doing that, though.

I am not sure whether anyone is using this file anymore.
@sebavan did you ever start using this file? Or do you still use a constants file inside Babylon? In the CTS, we migrated away from a constants file by using `as const` on our string literals, to narrow the types from the default `: string` to e.g. `: 'uniform-buffer'`. That fixed our type inference problems.

**Comment by darionco** [comment]
This one has been fixed, should be closed.

**Comment by kainino0x** [comment]
thanks!
