### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by mcclure** [gpuweb/types#37]
Your README gives the instruction

`npm install --save @webgpu/types`

…but explains no further. I run this, then run `webpack`…

```
ERROR in /Users/mcc/work/h/hello-more/webgpu/src/index.tsx
./src/index.tsx
[tsl] ERROR in /Users/mcc/work/h/hello-more/webgpu/src/index.tsx(58,18)
      TS2339: Property 'gpu' does not exist on type 'Navigator'.
```

Is there another step?

I remember like five years ago there was some kind of magic `///include "path.d.ts"` with a weird syntax that you used in TypeScript to import ambient d.ts files but ever since the `@types` regime came I've only got types through the normal import statement. I'm not sure how that works since these are ambient definitions.

Firing at random I tried various things like `import * as WebGPU from "@types/WebGPU"` and got various errors like

```
ERROR in /Users/mcc/work/h/hello-more/webgpu/src/index.tsx
./src/index.tsx
[tsl] ERROR in /Users/mcc/work/h/hello-more/webgpu/src/index.tsx(3,25)
      TS2307: Cannot find module 'WebGPU' or its corresponding type declarations.
```

***"Expected behavior"***: There should be a line in the README explaining how to use these types. If I got confused probably so would other people.

**Comment by mcclure** [comment]
Some nice people on "Twitter" helped me. I found this works:

```
/// <reference path="../node_modules/@webgpu/types/dist/index.d.ts" />
```

Which feels… wrong…

And someone dug up an existing project that added the node_modules path to tsconfig.json:

https://github.com/austinEng/webgpu-samples/blob/main/tsconfig.json

I added the same string to my tsconfig.json and this fixed things.

Neither of these solutions feels "obvious", if the tsconfig.json approach is the intended one maybe it should go in the README?

**Comment by mcclure** [comment]
Another nice person on Twitter is suggesting that if you added a "package.json/module" to your dist directory the user would not need to modify their tsconfig. I am not familiar with this mechanism but this is how he describes it: https://twitter.com/Eramdam/status/1347795627141341186

**Comment by kainino0x** [comment]
Hi mcc! Thanks for the report. I will fully admit that this is probably misconfigured because I don't know what I'm doing (I find it extremely hard to find the """right""" way to do things in the JS ecosystem, especially when you're off the beaten path like we are here since the type definitions are "ambient" as you pointed out). Often ambient definitions are done inside TypeScript's built-in typing via ["lib"](https://www.typescriptlang.org/tsconfig#lib). Since WebGPU is not yet stable it hasn't made sense to upstream these types into TypeScript. But there are many libraries (like JQuery) which also need to define global objects (like `$`) so I should try to match those.

As another reference here is how it's used inside the WebGPU conformance test repo: there's a [single file](https://github.com/gpuweb/cts/blob/main/src/webgpu/util/navigator_gpu.ts) in the "common" code which does `/// <reference types="@webgpu/types" />`
(ignore the weird actual code, where it tries to abstract away `navigator.gpu`; that's only needed for non-browser bindings which we don't quite have yet anyway).
I don't think this pattern really works well for most projects as they're not guaranteed to include a common file in every file that uses WebGPU. The pattern used by webgpu-samples is probably a lot more general. I will look into this a bit more to make sure this in the right approach, and get this documented. Thanks again!

**Comment by kainino0x** [comment]
Oh, fwiw, I *think* a valid alternative to
`<reference types="@webgpu/types" />`
is
`import {} from "@webgpu/types";`

**Comment by pjoe** [comment]
I found adding the following to `tsconfig.json` works for me:

```json
"typeRoots": ["node_modules/@types", "node_modules/@webgpu/types"],
```

Maybe worth mentioning something in the README on usage?
